### PR TITLE
Update 26Mhz TCXO LCSC in BOM

### PR DESCRIPTION
**Pull request by AiyionPrime**
We couldn't find the current id, but found another, which is referenced in the readme already.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
Mind telling us what went wrong?

**Comment by Jana-Marie** [comment]
Oh sorry for not doing such right away, nothing went wrong, I appreciate your pull request a lot! ❤️ 

It just happened that I updated the BOM anyways and in that also updating the TXCO. Sorry for just closing this like that

**Comment by Jana-Marie** [comment]
Oh huh, I cannot find the C-Number you provided with JLC

**Comment by AiyionPrime** [comment]
We'll look into it until the end of the week.
Thanks for your fast feedback :)

**Pull request closed without merging**
